h1 = figure(1),
subplot(5,2,1),imshow(complete),xlabel('Complete'),...
    subplot(5,2,2),imshow(torso),xlabel('Torso'),...
    subplot(5,2,3),imshow(wing),xlabel('Wing'),...
    subplot(5,2,4),imshow(tt),xlabel('Tail&Torso'),...
    subplot(5,2,5),imshow(head),xlabel('Head'),...
    subplot(5,2,6),imshow(lf),xlabel('Leg&Foot'),...
    subplot(5,2,7),imshow(tlf),xlabel('Torso&Leg&Foot'),...
    subplot(5,2,8),imshow(tail),xlabel('Tail'),...
    subplot(5,2,9),imshow(nt),xlabel('Neck&Torso'),...
subplot(5,2,10),imshow(hnt),xlabel('Head&Neck&Torso'),

h2 = figure(2),
subplot(2,5,1),imshow(complete),xlabel('Complete'),...
    subplot(2,5,2),imshow(torso),xlabel('Torso'),...
    subplot(2,5,3),imshow(wing),xlabel('Wing'),...
    subplot(2,5,4),imshow(tt),xlabel('Tail&Torso'),...
    subplot(2,5,5),imshow(head),xlabel('Head'),...
    subplot(2,5,6),imshow(lf),xlabel('Leg&Foot'),...
    subplot(2,5,7),imshow(tlf),xlabel('Torso&Leg&Foot'),...
    subplot(2,5,8),imshow(tail),xlabel('Tail'),...
    subplot(2,5,9),imshow(nt),xlabel('Neck&Torso'),...
subplot(2,5,10),imshow(hnt),xlabel('Head&Neck&Torso'),


export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/bird.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/bird.png -q101


h3 = figure(3),
subplot(2,5,2),imshow(complete),xlabel('Complete'),...
    subplot(2,5,4),imshow(torso),xlabel('Torso'),...
    subplot(2,5,3),imshow(lp),xlabel('Leg&Paw'),...
    subplot(2,5,1),imshow(tt),xlabel('Tail&Torso'),...
    subplot(2,5,5),imshow(head),xlabel('Head'),...
    subplot(2,5,8),imshow(tlp),xlabel('Torso&Leg&Paw'),...
    subplot(2,5,9),imshow(tail),xlabel('Tail'),...
    subplot(2,5,7),imshow(nt),xlabel('Neck&Torso'),...
subplot(2,5,6),imshow(hnt),xlabel('Head&Neck&Torso'),


export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/cat.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/cat.png -q101


h4 = figure(4),
subplot(2,5,5),imshow(complete),xlabel('Complete'),...
    subplot(2,5,1),imshow(torso),xlabel('Torso'),...
    subplot(2,5,3),imshow(leg),xlabel('Leg'),...
    subplot(2,5,4),imshow(tt),xlabel('Tail&Torso'),...
    subplot(2,5,2),imshow(head),xlabel('Head'),...
    subplot(2,5,8),imshow(torsoleg),xlabel('Torso&Leg'),...
    subplot(2,5,6),imshow(tail),xlabel('Tail'),...
    subplot(2,5,7),imshow(nt),xlabel('Neck&Torso'),...
subplot(2,5,9),imshow(hnt),xlabel('Head&Neck&Torso'),


export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/cow.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/cow.png -q101


h5 = figure(5),
subplot(2,5,5),imshow(frontside),xlabel('Front Side'),...
    subplot(2,5,1),imshow(leftside),xlabel('Left Side'),...
    subplot(2,5,3),imshow(rightside),xlabel('Right Side'),...
    subplot(2,5,4),imshow(backside),xlabel('Back Side'),...
    subplot(2,5,2),imshow(roofside),xlabel('Roof Side'),...
    subplot(2,5,8),imshow(fliplate),xlabel('Front Licence Plate'),...
    subplot(2,5,6),imshow(bliplate),xlabel('Back Licence Plate'),...
    subplot(2,5,7),imshow(complete),xlabel('Complete'),...
subplot(2,5,9),imshow(wheel),xlabel('Wheel'),


export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/car.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/car.png -q101

h6 = figure(6),
subplot(2,5,5),imshow(head),xlabel('Head'),...
    subplot(2,5,1),imshow(lp),xlabel('Leg&Paw'),...
    subplot(2,5,3),imshow(tail),xlabel('Tail'),...
    subplot(2,5,4),imshow(torso),xlabel('Torso'),...
    subplot(2,5,2),imshow(hnt),xlabel('Head&Neck&Torso'),...
    subplot(2,5,8),imshow(tt),xlabel('Torso&Tail'),...
    subplot(2,5,6),imshow(nt),xlabel('Neck&Torso'),...
    subplot(2,5,7),imshow(complete),xlabel('Complete'),...
subplot(2,5,9),imshow(tlp),xlabel('Torso&Leg&Paw'),


export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/dog.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/dog.png -q101

h7 = figure(7),
subplot(2,5,6),imshow(head),xlabel('Head'),...
    subplot(2,5,1),imshow(lh),xlabel('Leg&Hoof'),...
    subplot(2,5,3),imshow(tail),xlabel('Tail'),...
    subplot(2,5,2),imshow(torso),xlabel('Torso'),...
    subplot(2,5,4),imshow(hnt),xlabel('Head&Neck&Torso'),...
    subplot(2,5,8),imshow(tt),xlabel('Torso&Tail'),...
    subplot(2,5,5),imshow(nt),xlabel('Neck&Torso'),...
    subplot(2,5,7),imshow(complete),xlabel('Complete'),...
subplot(2,5,9),imshow(tlh),xlabel('Torso&Leg&Hoof'),


export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/horse.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/horse.png -q101


h8 = figure(8),
subplot(3,4,5),imshow(hair),xlabel('Hair'),...
    subplot(3,4,7),imshow(head),xlabel('Head'),...
    subplot(3,4,8),imshow(hand),xlabel('Hand'),...
    subplot(3,4,2),imshow(arm),xlabel('Arm'),...
    subplot(3,4,3),imshow(leg),xlabel('Leg'),...
    subplot(3,4,4),imshow(torso),xlabel('Torso'),...
    subplot(3,4,6),imshow(nt),xlabel('Neck&Torso'),...
    subplot(3,4,9),imshow(complete),xlabel('Complete'),...
subplot(3,4,1),imshow(hnt),xlabel('Head&Neck&Torso'),
subplot(3,4,10),imshow(torsoleg),xlabel('Torso&Leg'),
subplot(3,4,11),imshow(at),xlabel('Torso&Arm'),



export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/person.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/person.png -q101


h9 = figure(9),
subplot(2,5,6),imshow(head),xlabel('Head'),...
    subplot(2,5,1),imshow(leg),xlabel('Leg'),...
    subplot(2,5,3),imshow(tail),xlabel('Tail'),...
    subplot(2,5,2),imshow(torso),xlabel('Torso'),...
    subplot(2,5,4),imshow(hnt),xlabel('Head&Neck&Torso'),...
    subplot(2,5,8),imshow(tt),xlabel('Torso&Tail'),...
    subplot(2,5,5),imshow(nt),xlabel('Neck&Torso'),...
    subplot(2,5,7),imshow(complete),xlabel('Complete'),...
subplot(2,5,9),imshow(torsoleg),xlabel('Torso&Leg'),


export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/sheep.pdf -transparent
export_fig /home/berksevilmis/workspace/proposalRankingProject/dataSets/trainval/guiVisuals/sheep.png -q101


